

octopus:
  environments:
    - production
  production:
    je:
      adapter: mysql2
      host: localhost
      username: root
      password: admin
      pool: 10
      database: jobenfance
      socket: /var/run/mysqld/mysqld.sock

    jd:
      adapter: mysql2
      host: localhost
      username: root
      password: admin
      pool: 10
      database: jobdependance
      socket: /var/run/mysqld/mysqld.sock

      